 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: frontend
 spec:
   selector:
     matchLabels:
       app: guestbook
       tier: frontend
   replicas: 3
   template:
     metadata:
       labels:
         app: guestbook
         tier: frontend
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: "node1"
                 operator: In
                 values: ["TheChosenOne"]
       containers:
       - name: php-redis
         image: eyesoncloud/gb-frontend:v4
         ports:
         - containerPort: 80
