apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  labels: 
    app: blue-webserver
spec:
  type: NodePort
  selector:
    app: webserver
    ver: blue
  ports:
  - protocol: TCP
    nodePort: 30010
    port: 80
    targetPort: 80
