apiVersion: apps/v1
kind: Deployment
metadata:
  name: normal-app
  labels:
    app: normal-application
spec:
  selector:
    matchLabels:
      app: normal-application
  replicas: 6
  template:
    metadata:
      labels:
        app: normal-application
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
