apiVersion: v1
data:
  service-frontend-nginx.conf: |
    # The identifier Backend is internal to nginx, and used to name this specific upstream
    upstream Backend {
        # "backend-service" is the internal DNS name used by the backend Service inside Kubernetes
       server mysql;
    }

    server {
        listen 80;

        location / {
            # The following statement will proxy traffic to the upstream named Backend
            proxy_pass http://Backend;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
  namespace: frontend-ns
