apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: my.kubernetes.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-blue-service
            port:
              number: 80
