apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-demo
  namespace: eoc-demo
spec:
  containers:
  - name: constraints-mem-demo-ctr
    image: nginx
    resources:
      requests:
        memory: "600Mi"
      limits:
        memory: "800Mi"
