apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-demo-3
  namespace: eoc-demo
spec:
  containers:
  - name: constraints-mem-demo-3-ctr
    image: nginx
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "800Mi"
      
