apiVersion: v1
kind: Pod
metadata:
  name: node-app
spec:
  containers:
    - name: node-container
      image: node:16
      command: ["node", "-e", "
        const dbConnection = process.env.DB_CONNECTION_STRING;
        if (!dbConnection) {
          throw new Error('Missing DB_CONNECTION_STRING environment variable');
        }
        require('http').createServer((req, res) => res.end('Application started successfully')).listen(8080);
      "]
      env:
        - name: NODE_ENV
          value: "production"
        # Missing DB_CONNECTION_STRING here will cause the app to crash
      ports:
        - containerPort: 8080
