apiVersion: v1
kind: Pod
metadata:
  name: non-root-user-pod-demo
  labels: 
    app: security-context
spec:
  securityContext:
    runAsNonRoot: true   # Ensures the container runs as a non-root user
  volumes:
  - name: demo-volume
    emptyDir: {}        
  containers:
  - name: non-root-user-demo
    image: nginx:alpine    
    command: [ "tail", "-f", "/dev/null" ]  
    volumeMounts:
    - name: demo-volume
      mountPath: /data/demo 
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL    
