apiVersion: v1
kind: Service
metadata:
  name: ambassador-service
  labels:
    app: ambassador-app
spec:
  selector:
    app: ambassador-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
