apiVersion: v1
kind: Pod
metadata:
  name: pod-share-process
spec:
  shareProcessNamespace: true  # Enable shared process namespace
  containers:
  - name: nginx
    image: nginx
  - name: shell
    image: busybox:1.28
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE  # Required to send signals to nginx process
    stdin: true
    tty: true
