apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-demo
spec:
  containers:
    - name: main-application
      image: nginx
      volumeMounts:
        - name: sharedstorage
          mountPath: /var/log/nginx  
          
    - name: sidecar-container
      image: busybox
      command: ["sh","-c","while true; do cat /var/log/nginx/access.log; sleep 5; done"]
      
      volumeMounts:
        - name: sharedstorage
          mountPath: /var/log/nginx
  volumes:
  - name: sharedstorage
    emptyDir: {}
