apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo
spec:
  containers:
  - name: nginx
    image: nginx
    
    volumeMounts:
    - name: hostpathvolume
      mountPath: /usr/share/nginx/html
      
  initContainers:
  - name: busybox
    image: busybox
   
    volumeMounts:
    - name: hostpathvolume
      mountPath: "/hostpathmount"
      
    command: ["/bin/sh"]
    args: ["-c", "echo '<html><h1>Hello, This Webpage was created by Init Container</h1><html>' >> /hostpathmount/index.html"]
  
  volumes:
  - name: hostpathvolume
    hostPath:
      path: /webstorage
