apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany  # Adjust the access mode as needed
  nfs:
    path: /srv/nfs/kubedata  # Path to the exported NFS directory
    server: 192.168.100.11
