apiVersion: v1
kind: Pod
metadata:
  name: seccomp-app
  namespace: default
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
    securityContext:
      seccompProfile:
        type: Localhost
        localhostProfile: "my-profile.json"
