apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: logging-app
spec:
  type: NodePort
  selector:
    app: sb-web-app #POD label
  ports:
    - port: 80
      targetPort: 808
