apiVersion: v1
kind: Pod
metadata:
  name: share-process
spec:
  containers:
  - name: nginx
    image: nginx
  - name: shell
    image: busybox:1.28
    command: ["sleep", "3600"]
    stdin: true
    tty: true
