apiVersion: v1
kind: Pod
metadata:
  name: mtdir-pod
spec:
  containers:
  - name: myvolumes-container
    image: alpine
    
    command: [    'sh', '-c', 'echo The Bench Container 1 is Running ; sleep 3600']
    
    volumeMounts:
    - mountPath: /demo
      name: demo-volume
 
  volumes:
   - name: demo-volume
     emptyDir: {}
