apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    app: webserver
spec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: webserver
  containers:
    - name: nginx
      image: nginx
